name: QA

on:
  pull_request:
  push:
    branches:
      - "**" # matches every branch
      - "!main" # excludes main
  workflow_call:

jobs:
  qa-branch:
    name: Run QA
    # We don't need to run this on Renovate PRs. We will already test the `renovate/foo` branch.
    if: github.event_name != 'pull_request' || github.actor != 'renovate[bot]'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4

      - name: Select NodeJS version
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        env:
          # renovate: datasource=docker depName=node versioning=node
          NODE_VERSION: "20.13.1"
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Check constraints
        run: yarn constraints

      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

  qa-docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Select NodeJS version
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        env:
          # renovate: datasource=docker depName=node versioning=node
          NODE_VERSION: "20.13.1"
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Build documentation
        run: yarn docs:build

  qa-successful:
    needs:
      - qa-branch
      - qa-docs
    name: Evaluate QA results
    if: ( success() || failure() )
    runs-on: ubuntu-22.04
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
